// Website Action
const WebsiteActionTypes = {
  TOGGLE_LIGHT_MODE: "WEBSITE/TOGGLE_LIGHT_MODE",
  TOGGLE_ABOUT_MODAL_VISIBLE: "WEBSITE/TOGGLE_ABOUT_MODAL_VISIBLE",
  SET_PAGE_LOADING: "WEBSITE/SET_PAGE_LOADING",
  REMOVE_PAGE_LOADING: "WEBSITE/REMOVE_PAGE_LOADING",
  CHANGE_LANGUAGE: "WEBSITE/CHANGE_LANGUAGE"
};

export default WebsiteActionTypes;
