// Email Action
const EmailActionTypes = {
  SEND_EMAIL: "EMAIL/SEND_EMAIL",
  EMAIL_SUCCESS: "EMAIL/EMAIL_SUCCESS",
  EMAIL_FAIL: "EMAIL/EMAIL_FAIL",
  SEND_CONFIRMATION_EMAIL: "EMAIL/SEND_CONFIRMATION_EMAIL",
  CONFIRMATION_EMAIL_SUCCESS: "EMAIL/CONFIRMATION_EMAIL_SUCCESS",
  CONFIRMATION_EMAIL_FAIL: "EMAIL/CONFIRMATION_EMAIL_FAIL"
};

export default EmailActionTypes;
