name: MasterDeployCI
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on ubuntu-latest
    strategy:
        matrix:
            node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version}}
    - name: Install Packages
      run: yarn
    - name: Check Eslint
      run: yarn run eslint
    - name: Test
      run: yarn test
    - name: Deploy GH Pages
      run: |
        git config --global user.email ${{secrets.USER_EMAIL}}
        git config --global user.name ${{secrets.USER_USERNAME}}
        git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/${{secrets.USER_USERNAME}}/react-portifolio.git
        yarn run deploy
    - name: Updating Domain
      run: echo "Update Domain"